[selectors]
login_button = "[data-qa='submit-button']"
region_code = "[data-qa='magritte-phone-input-calling-code']"
region_list = "[data-qa='magritte-select-option-list']"
phone_input = "[data-qa='magritte-phone-input-national-number-input']"
email_option = "Почта"
email_input = "[data-qa='applicant-login-input-email']"
password_button = "[data-qa='expand-login-by-password']"
password_input =  "[data-qa='applicant-login-input-password']"
pagination_block = "[data-qa='pager-block']"
search_button = "[data-qa='searchVacancy-button']"
search_input = "[data-qa='search-input']"
vacancy_result = "[data-qa='vacancy-serp__results']"
vacancy_links = "a[data-qa='serp-item__title']"
vacancy_response = "[data-qa='vacancy-response-link-top']"
vacancy_not_found = "Попробуйте другие варианты поискового запроса или уберите фильтры"
vacancy_applied = "Вы откликнулись"
additional_info = "[data-qa='additional-data-collector__popup-title']"
additional_info_close = "[data-qa='additional-data-collector__popup-close']"
login_error = "Неправильные данные для входа. Пожалуйста, попробуйте снова."
captcha_message_one = "Пройдите капчу"
captcha_message_two = "Пожалуйста, подтвердите, что вы не робот"

[logs]
file_log_level = "INFO"

[retries]
max_connection_attempts = 3
max_proxy_get_attempts = 3

[timeouts]
connection_timeout = 30
element_timeout = 15


[network]
sleep_between_actions = 2
sleep_between_requests_min = 0.5
sleep_between_requests_max = 2

[parsing]
hh_login_url = "https://hh.ru/account/login"
